# Nimble Streamer Management Configuration
# For BreadCall WHIP/WHEP SFU

# Management API settings
management_listen_interfaces = 0.0.0.0
management_port = 8082
management_token = b5a9073bd216aef49e2fa71381e337c0
